### ISSUE TITLE
Error to connect from client

### ISSUE THREAD

**Issue by itroeix** [jsonmona/twilight#1]
When I try to connect from the client and I put the port that it indicates (6498) and the local ip, it turns black, here are the commands that I execute:
server.exe
client.exe 192.168.0.X 6498 (the X is the number of my device)
But when I run the debug.exe it goes fine.

**Comment by jsonmona** [comment]
That's because current server only binds to 127.0.0.1 (see [this](https://github.com/jsonmona/twilight/blob/46f9bf151129ab5d8d1a99eee4e3347a409fc931/src/server/twilight_server.rs#L60)). Try using that address instead.

I've done it this way because I figured it isn't a good idea to expose this yet-rudimentary server to the internet.
